Capture NServiceBus endpoint startup logs before logger is available
Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus pull request #239
Opened 2021-07-29 05:34 UTC by mikeminutillo

Closes #238 

Uses the same technique as [NServiceBus.Extensions.Hosting](https://github.com/Particular/NServiceBus.Extensions.Hosting) to capture all log messages in deferred loggers until an `ILogger` instance is available.

2021-07-29 06:22 UTC, SeanFeldman approved these changes

2021-08-04 08:20 UTC, timbussmann requested changes

2021-08-04 08:20 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
>              FunctionsLoggerFactory.Instance.SetCurrentLogger(functionsLogger);
we'd have to change the logger on the `LogManager` here back to the Functions logger, otherwise the Deferred Factory remains the default logger I think

2021-08-04 08:20 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
> +            DeferredLoggerFactory.Instance.FlushAll(FunctionsLoggerFactory.Instance);
with this approach, I'm not really sure why need the whole AsyncLocal stuff in the Functions logger anymore. Tbh it feels like we could combine those two loggers into one, but I'm also ok to keep them separate for now to keep them simpler.

2021-08-04 08:41 UTC, HEskandari approved these changes

2021-08-05 07:43 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
> +            DeferredLoggerFactory.Instance.FlushAll(FunctionsLoggerFactory.Instance);
I think it's still possible that the same Azure Function can be triggered multiple times in parallel within the same instance. I don't know if the internal logging mechanism keeps those separate. If it does then the async local is still required.

I did look at combining these but it gets complicated as the MS Extensions `ILogger` uses generics for it's log state, which makes it harder to store them in a deferred way.

2021-08-05 07:47 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
> +            DeferredLoggerFactory.Instance.FlushAll(FunctionsLoggerFactory.Instance);
Just typing that made me realize I can defer it in NSB format and flush it in MS Extensions format. I will take another pass.

2021-08-05 07:47 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
>              FunctionsLoggerFactory.Instance.SetCurrentLogger(functionsLogger);
You are right. I used to have something in the `FunctionEndpoint` factory method that did this swap but I dropped it because we can't guarantee that's only way it gets constructed. I missed putting it back in here.

2021-08-05 07:53 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
>              FunctionsLoggerFactory.Instance.SetCurrentLogger(functionsLogger);
Actually, it _is_ the only way to get a `FunctionEndpoint`. It's constructor is internal. :)
That simplifies things

2021-08-06 05:43 UTC, mikeminutillo commented
Collapsed back into a single logger that can defer until it is handed a logger via a call to `Process()`. Note that if you don't provide a logger then we put a `NullLogger` in place. This prevents deferred logs from building up indefinitely.

There _is_ still a case where logs could grow indefinitely. That's where you're using `FunctionEndpoint` but never calling `Process()`.

2021-08-06 06:44 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
> +            FunctionsLoggerFactory.Instance.SetCurrentLogger(functionsLogger ?? NullLogger.Instance);
could we do that fallback inside `SetCurrentLogger`?

2021-08-06 06:44 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +            Flush(concreteLogger);
what's the scenario that requires Flush to be called here given that Flush is also called when setting the logger in `SetCurrentLogger`?

2021-08-06 07:13 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs
> +            FunctionsLoggerFactory.Instance.SetCurrentLogger(functionsLogger ?? NullLogger.Instance);
Done

2021-08-06 07:13 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +            Flush(concreteLogger);
I can't think of one. The flush in `SetCurrentLogger` was added during testing.

2021-08-06 07:46 UTC, mikeminutillo commented
Smoke testing and this appears to work 

![image](https://user-images.githubusercontent.com/124014/128475622-e46f7f9b-062d-489c-8704-6e18b3f9910e.png)

This also highlights the fact that all of the sending/publishing APIs can also be passed a logger and this works as expected.

2021-08-06 08:25 UTC, HEskandari approved these changes

2021-08-06 11:52 UTC, timbussmann approved these changes
one thought but otherwise LGTM

2021-08-06 11:52 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +                deferredMessageLogs.Enqueue((level, message));
is there a potential race condition in a case where a caller entered the if condition and then concurrently the logger is set and the queues are emptied before the caller enters the enqueue method, essentially causing a "log loss"?

2021-08-06 12:55 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +                deferredMessageLogs.Enqueue((level, message));
The concrete logger comes from an async local. If another thread sets it then it will be in that threads async local context so it should not affect this one.

2021-08-06 15:27 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +                deferredMessageLogs.Enqueue((level, message));
hm not sure that's what I mean, here's what I was thinking about:

Thread1(T1): checks `concreteLogger`, value is `null`, enters if condition.
Thread2(T2): calls `SetCurrentLogger`
T2: Sets logger value to logger instance
T2: Subsequentlly calls `Flush`
T2: Flush empties all `defferedMessageLogs` entries
T2: completes
T1: adds log entry to `defferedMessageLogs` as part of the previously entered if-block. `defferedMessageLogs` isn't read anymore.

2021-08-09 02:55 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +                deferredMessageLogs.Enqueue((level, message));
We used to flush on every log call which would resolve this problem. I can put that back. Given that the deferred logger will usually be empty, this shoud be quick. We'd create three enumerators, for every log call which we can probably avoid if we check the queue length before enumerating them.

2021-08-09 02:56 UTC, mikeminutillo commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +                deferredMessageLogs.Enqueue((level, message));
Actually, because it's a queue we only ever `TryDequeue`. There's no enumerator created. This should be quick.

2021-08-09 07:17 UTC, timbussmann commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Logging/Logger.cs
> +                deferredMessageLogs.Enqueue((level, message));
not really sure that's worthwhile though. Arguably, there shouldn't really be log statements being created while the logger is being replaced as we haven't started processing messages yet and the endpoint started up already, so maybe this is something that doesn't necessarily need to be fixed. The only potential log statements would come from sort of background job which shouldn't really happen without an active message pump.

2021-08-09 11:16 UTC, timbussmann commented
merging this for now to start testing. @mikeminutillo if you want to follow-up on our discussion regarding the race condition, we can also do that via a separate PR I think

2021-08-09 11:16 UTC, merged