Add Outbox validation
Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus pull request #585
Opened 2022-12-12 12:24 UTC by SzymonPobiega

2022-12-12 12:49 UTC, andreasohlund commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Serverless/OutboxProcessingValidationBehavior.cs
> +        if (outboxEnabled && state.IsAtomic)
We could also check for the presence of the commitable transaction but perhaps this is more explicit?

2022-12-13 08:06 UTC, SzymonPobiega commented on src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Serverless/OutboxProcessingValidationBehavior.cs
> +        if (outboxEnabled && state.IsAtomic)
Yeah, unless there is a significant performance impact of having that state object, I prefer the explicit version.

2022-12-14 13:01 UTC, WojcikMike approved these changes

2022-12-16 09:57 UTC, andreasohlund approved these changes

2022-12-16 09:57 UTC, andreasohlund commented on src/ServiceBus.AcceptanceTests/When_using_processatomic_with_outbox.cs
> +                    //configuration.AdvancedConfiguration.Recoverability().Immediate(x => x.NumberOfRetries(1));
Remove

2022-12-16 12:08 UTC, andreasohlund requested changes

2022-12-16 14:35 UTC, andreasohlund approved these changes

2022-12-19 07:35 UTC, andreasohlund commented
@SzymonPobiega you need to adjust the test to the new ex message

2022-12-19 07:53 UTC, merged